// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: chat_gpt_new_gui

#include "app_sr.h"
#include "ui.h"
#include "app_ui_ctrl.h"
#include "OpenAI.h"
#include "esp_ota_ops.h"
#include "esp_system.h"
#include "esp_log.h"
#include "app_weather.h"
#include "settings.h"
#include "app_audio.h"
#include <time.h>
#include <sys/time.h>
#include "tts_api.h"
#include "audio_player.h"
#include "bsp/esp-bsp.h"
#include "bsp_board.h"
#include "app_wifi.h"
#include "nvs_flash.h"
#include "nvs.h"
extern int8_t Volume_value;
static char *TAG = "Events";
extern uint8_t Sr_task_flag;
extern bool ui_event_flag = false;
struct timeval tv;
struct tm* timeinfo;
static const char *NVS_MEMU = "memu data";
static bool music_flag = false;
static uint8_t music_change_flag = 0;
void chang_music_name();
//处理语音命令的函数,传入参数为命令ID
void sr_command_task(uint8_t command_id)
{
    // 打印命令ID
    ESP_LOGI(TAG, "command_id:%d", command_id);
        switch(command_id)
        {   
            case 0:
            ui_event_flag = true;
            ESP_LOGI(TAG, "da kai zhi neng dui hua");
            //切换到Ai聊天页面
            _ui_screen_change(&ui_AIChat, LV_SCR_LOAD_ANIM_FADE_ON, 50, 10, &ui_AIChat_screen_init);
            //播放动画
            AIChatGO_Animation(ui_AIChat, 0);
            //自动唤醒aI聊天，播放提示语音
            lv_label_set_text(ui_Label1, "我在听~~~");
            app_sr_start_once();//启动一次SR

            break;
            case 1:
            ui_event_flag = true;
            ESP_LOGI(TAG, "da kai shi jian");
         
            //切换到Ai聊天页面
            _ui_screen_change(&ui_AIChat, LV_SCR_LOAD_ANIM_FADE_ON, 50, 10, &ui_AIChat_screen_init);
            //播放动画
            AIChatGO_Animation(ui_AIChat, 0);
            //不自动唤醒aI聊天
            //播放时间提示语音
            //     // struct timeval tv;
            //     gettimeofday(&tv, NULL);  // 获取当前时间
            //     // struct tm* timeinfo;
            //     timeinfo = localtime(&tv.tv_sec);  // 将时间转换为本地时间
            // char *time_str1 = heap_caps_malloc(50, MALLOC_CAP_DEFAULT);
            // sprintf(time_str1, "当前时间为%d时%d分。", timeinfo->tm_hour, timeinfo->tm_min);
            // if(tts_respond(time_str1) == ESP_OK){
            //     ESP_LOGI(TAG, "timetts_OK\n");
            // }
            // free(time_str1);
            break;
            case 2:
            ui_event_flag = true;
            ESP_LOGI(TAG, "da kai ri li");
       
            //切换到日历页面
            _ui_screen_change(&ui_Calendar, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Calendar_screen_init);
            // //播放日历语音
            //     // struct timeval tv;
            //     gettimeofday(&tv, NULL);  // 获取当前时间
            //     // struct tm* timeinfo;
            //     timeinfo = localtime(&tv.tv_sec);  // 将时间转换为本地时间
            // char *time_str2 = heap_caps_malloc(50, MALLOC_CAP_DEFAULT);
            // sprintf(time_str2, "当前日期为%d年%d月%d日。", timeinfo->tm_year+1900, timeinfo->tm_mon+1, timeinfo->tm_mday);
            // if(tts_respond(time_str2) == ESP_OK){
            //     ESP_LOGI(TAG, "datatts_OK\n");
            // }
            // free(time_str2);
            break;
            case 3:
            ui_event_flag = true;
            ESP_LOGI(TAG, "da kai yin yue");
        
            //切换到音乐页面
            _ui_screen_change(&ui_Music, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Music_screen_init);
            break;
            case 4:
            ui_event_flag = true;
            ESP_LOGI(TAG, "bo fang yin yue");
            // 打开等待提示音文件
            if(music_change_flag == 0){
                FILE *fp = fopen("/spiffs/Rubia.mp3", "r");
                if (fp) {
                    audio_player_play(fp); // 播放
                }
            }
            else{
                FILE *fp = fopen("/spiffs/Hope.mp3", "r");
                if (fp) {
                    audio_player_play(fp); // 播放
                }      
            }
            music_flag = true;
            //开始播放音乐，
            break;
            case 5:
            ui_event_flag = true;
            ESP_LOGI(TAG, "ting zhi bo fang");
            audio_player_stop();//停止播放音乐
            music_flag = false;
            break;
            case 6:
            ui_event_flag = true;
            ESP_LOGI(TAG, "zeng da sheng yin");

            Volume_value += 5;
            if(Volume_value > 100){
                Volume_value = 100;
                // char *volume_str = "音量已最大。";
                // if(tts_respond(volume_str) == ESP_OK){
                // ESP_LOGI(TAG, "voicettsrtts_OK\n");
                // }
            }
            else{
                bsp_codec_mute_set(true); // 静音
                bsp_codec_mute_set(false); // 取消静音
                bsp_codec_volume_set(Volume_value,NULL);//增加音量
            }
            break;
            case 7:
            ui_event_flag = true;
            ESP_LOGI(TAG, "jian xiao sheng yin");
            Volume_value -= 5;
            if(Volume_value <= 0){
                Volume_value = 0;
                // char *volume_str = "音量已最小。";
                // if(tts_respond(volume_str) == ESP_OK){
                // ESP_LOGI(TAG, "voicettsrtts_OK\n");
                // }
            }
                bsp_codec_mute_set(true); // 静音
                bsp_codec_mute_set(false); // 取消静音
                bsp_codec_volume_set(Volume_value,NULL);//减少音量
            break;
            case 8:
            ui_event_flag = true;
            ESP_LOGI(TAG, "da kai tian qi");
    
            //切换到天气页面
            _ui_screen_change(&ui_Weather, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Weather_screen_init);
        //     //播放天气语音
        //         weather_flag = 1;
        //         weather_data_t *weather_data = http_weather_data_create();  // 从堆中分配天气数据
        //         /* Perform an HTTP GET request with the weather data */
        //         sys_param_t *sys_param = settings_get_parameter();  // 获取系统参数
        //         ESP_ERROR_CHECK(http_get_with_url(sys_param->weather_url, weather_data));  // 执行HTTP GET请求获取天气数据
        //     char *weather_str = heap_caps_malloc(250, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT); // 格式化天气数据为字符串
        //    weather_flag = 0;
        //    ESP_ERROR_CHECK(http_weather_data_delete(weather_data));  // 释放天气数据资源
        //     sprintf(weather_str,"当前城市为%s,天气%s,当前温度为%d度,湿度百分之%d,%s%s。今日最高温度为%d度,最低温度为%d度。",weather_data->city,weather_data->text,*(weather_data->temp),*(weather_data->rh),weather_data->wind_dir,weather_data->wind_class,*(weather_data->high),*(weather_data->low));
        //     if(tts_respond(weather_str) == ESP_OK){
        //         ESP_LOGI(TAG, "weathertts_OK\n");
        //     }

            break;
            case 9:
            ui_event_flag = true;
            ESP_LOGI(TAG, "da kai bei wang lu");//可能需要优化
            //切换到备忘录页面
            
            _ui_screen_change(&ui_Memo, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Memo_screen_init);
            //播放语音,好的
            
            break;
            case 10:
            ui_event_flag = true;
            Sr_task_flag = 1;
            ESP_LOGI(TAG, "ji bei wang lu");
          _ui_screen_change(&ui_Memotext, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Memo_screen_init);
            //开始录音，把录音转文字后保存到备忘录
            break;
            case 11:
            ui_event_flag = true;
            ESP_LOGI(TAG, "da kai wang luo");

            //切换到wifi页面
            _ui_screen_change(&ui_WiFi, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_WiFi_screen_init);
            //播放语音,好的
            break;
            case 12:
            ui_event_flag = true;
            ESP_LOGI(TAG, "lian jie wang luo");
           
            //连接到WIFI
            //连接失败后，播放失败提示语音，切换到wifi页面
            _ui_screen_change(&ui_WiFi, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_WiFi_screen_init);
            send_network_event(1);
            break;
            case 13:
            ui_event_flag = true;
            ESP_LOGI(TAG, "xia yi sho");
            chang_music_name();
            break;
            case 14:
            ui_event_flag = true;
            ESP_LOGI(TAG, "shang yi yi sho");
            chang_music_name();
            //切换到语音设置页面
            //断开WIFI
            
            default:
            break;
        }
}

void ToListening(lv_event_t * e)
{
	// Your code here
    // app_sr_start_once();//启动一次SR
}
void chang_music_name()
{
    if(music_change_flag == 0){
        
    lv_label_set_text(ui_LabelMusicname, "Hope Is the Thing With Feathers");
    FILE *fp = fopen("/spiffs/Hope.mp3", "r");
                if (fp) {
                    audio_player_play(fp); // 播放
                } 
    music_change_flag = 1;
    }
    else{
        lv_label_set_text(ui_LabelMusicname, "Rubia");
        FILE *fp = fopen("/spiffs/Rubia.mp3", "r");
                if (fp) {
                    audio_player_play(fp); // 播放
                } 
        music_change_flag = 0;
    }

}
void Chgemusicup(lv_event_t * e)
{
    chang_music_name();
	// Your code here
}

void MusicStartatop(lv_event_t * e)
{
    if(music_change_flag == 0){
        if(music_flag == false){
            FILE *fp = fopen("/spiffs/Rubia.mp3", "r");
                if (fp) {
                    audio_player_play(fp); // 播放
                } 
            music_flag = true;
        }
        else{
            audio_player_stop();
            music_flag = false;
        }
    }
    else{
        if(music_flag == false){
            FILE *fp = fopen("/spiffs/Hope.mp3", "r");
                if (fp) {
                    audio_player_play(fp); // 播放
                } 
            music_flag = true;
        }
        else{
            audio_player_stop();
            music_flag = false;
        }
    }
	// Your code here
}

void ChgemusicDowm(lv_event_t * e)
{
    chang_music_name();
	// Your code here
}
extern bool memu_flag;
void SetMemotext(lv_event_t * e)
{
    nvs_handle handle;
    char memodata_num[20];
    lv_roller_get_selected_str(ui_MemoText,memodata_num,20);
    ESP_LOGI(TAG, "memodata_num:%s", memodata_num);
    //判断memodata_num是否为example1
    if(memu_flag == false){
        lv_textarea_set_text(ui_TextAreamemoname,"");
        lv_textarea_set_text(ui_TextAreamemotext,"");
    }
    else{

            // ESP_LOGI(TAG, "memodata_num", memodata_num);
    ESP_ERROR_CHECK( nvs_open( NVS_MEMU, NVS_READWRITE, &handle) );
    int8_t memodatam = 0;
    if(nvs_get_i8 (handle, "memo_num", &memodatam) == ESP_OK)
    {

        char *time_str2 = heap_caps_malloc(50, MALLOC_CAP_DEFAULT);
        char *data = heap_caps_malloc(512, MALLOC_CAP_DEFAULT);
        // ESP_ERROR_CHECK( nvs_set_str( handle, "text", time_str2) );
        // ESP_ERROR_CHECK( nvs_set_str( handle, "data", data) );
        lv_textarea_set_text(ui_TextAreamemoname,time_str2);
        lv_textarea_set_text(ui_TextAreamemotext,data);
        // lv_roller_set_options(ui_MemoText,time_str2,LV_ROLLER_MODE_NORMAL);
        ESP_ERROR_CHECK( nvs_commit(handle) );
        nvs_close(handle);
    }
    else{
        lv_textarea_set_text(ui_TextAreamemoname,"");
        lv_textarea_set_text(ui_TextAreamemotext,"");
    }
            
}
}

void CHANGEVolume(lv_event_t * e)
{
    char *volume_str = lv_label_get_text(ui_LabelVolumevalue);
    int volume_value = atoi(volume_str);
    bsp_codec_mute_set(true); // 静音
    bsp_codec_mute_set(false); // 取消静音
    bsp_codec_volume_set(volume_value,NULL);//设置音量
    ESP_LOGI(TAG, "volume_value:%d", volume_value);
	// Your code here
}

void DelMemotext(lv_event_t * e)
{
    //查找memo_title中的\n
    memu_flag = false;
        lv_textarea_add_text(ui_TextAreamemoname,"");
        lv_textarea_add_text(ui_TextAreamemotext,"");
                lv_roller_set_options(ui_MemoText,"esample1",LV_ROLLER_MODE_NORMAL);

        // lv_roller_set_options(ui_MemoText,"esample1",LV_ROLLER_MODE_NORMAL);
	// Your code here
}

void WIFIpassworrd(lv_event_t * e)
{
	// Your code here
}

void WIFIgoto(lv_event_t * e)
{
    char ssid[30] = {0};
    lv_dropdown_get_selected_str(ui_Dropdown1,ssid,30);
    // const char *password =  lv_textarea_get_text(ui_TextArea2);
    sys_param_t *sys_param = settings_get_parameter();
    //把ssid和密码保存到系统参数中
    //清空系统参数中的ssid和密码
    strcpy(sys_param->ssid,ssid);
    strcpy(sys_param->password,lv_textarea_get_text(ui_TextArea2));
    send_network_event(1);
	// Your code here
}

