// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp_box3

#include "../ui.h"


void ui_event_comp_ChangeAIChat1_ChangeAIChat1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_ChangeAIChat1 = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_AIChat, LV_SCR_LOAD_ANIM_FADE_ON, 50, 10, &ui_AIChat_screen_init);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        AIChatGO_Animation(ui_AIChat, 0);
    }
}

// COMPONENT ChangeAIChat1

lv_obj_t * ui_ChangeAIChat1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ChangeAIChat1;
    cui_ChangeAIChat1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_ChangeAIChat1, 313);
    lv_obj_set_height(cui_ChangeAIChat1, 16);
    lv_obj_set_x(cui_ChangeAIChat1, -1);
    lv_obj_set_y(cui_ChangeAIChat1, 108);
    lv_obj_set_align(cui_ChangeAIChat1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ChangeAIChat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ChangeAIChat1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ChangeAIChat1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_ChangeAIChat1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_ChangeAIChat1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label20;
    cui_Label20 = lv_label_create(cui_ChangeAIChat1);
    lv_obj_set_width(cui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label20, 2);
    lv_obj_set_y(cui_Label20, -5);
    lv_obj_set_align(cui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label20, "__________");
    lv_obj_set_style_text_color(cui_Label20, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CHANGEAICHAT1_NUM);
    children[UI_COMP_CHANGEAICHAT1_CHANGEAICHAT1] = cui_ChangeAIChat1;
    children[UI_COMP_CHANGEAICHAT1_LABEL20] = cui_Label20;
    lv_obj_add_event_cb(cui_ChangeAIChat1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ChangeAIChat1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_ChangeAIChat1, ui_event_comp_ChangeAIChat1_ChangeAIChat1, LV_EVENT_ALL, children);
    ui_comp_ChangeAIChat1_create_hook(cui_ChangeAIChat1);
    return cui_ChangeAIChat1;
}

