// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp_box3

#ifndef _UI_COMP_CHANGEAICHAT1_H
#define _UI_COMP_CHANGEAICHAT1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ChangeAIChat1
#define UI_COMP_CHANGEAICHAT1_CHANGEAICHAT1 0
#define UI_COMP_CHANGEAICHAT1_LABEL20 1
#define _UI_COMP_CHANGEAICHAT1_NUM 2
lv_obj_t * ui_ChangeAIChat1_create(lv_obj_t * comp_parent);
void ui_event_comp_ChangeAIChat1_ChangeAIChat1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
