// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp_box3

#include "../ui.h"

void ui_AIChat_screen_init(void)
{
    ui_AIChat = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AIChat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIChat, lv_color_hex(0xF5E6C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_AIChat, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIChat, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_tiled(ui_AIChat, false, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_AIChat);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -9);
    lv_obj_set_y(ui_Label1, 99);
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label1, "ZZZ~~~");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x0D0707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLable = lv_label_create(ui_AIChat);
    lv_obj_set_width(ui_TimeLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLable, 0);
    lv_obj_set_y(ui_TimeLable, 7);
    lv_obj_set_align(ui_TimeLable, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TimeLable, "00:00:00");
    lv_obj_set_style_text_font(ui_TimeLable, &ui_font_FontAI1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DataLabel = lv_label_create(ui_AIChat);
    lv_obj_set_width(ui_DataLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DataLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DataLabel, -3);
    lv_obj_set_y(ui_DataLabel, 66);
    lv_obj_set_align(ui_DataLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DataLabel, "2024/07/18");
    lv_obj_set_style_text_font(ui_DataLabel, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22WIFI = lv_label_create(ui_AIChat);
    lv_obj_set_width(ui_Label22WIFI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22WIFI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22WIFI, 14);
    lv_obj_set_y(ui_Label22WIFI, 101);
    lv_label_set_text(ui_Label22WIFI, "wiFi未连接");
    lv_obj_set_style_text_font(ui_Label22WIFI, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWIFIhiden = lv_obj_create(ui_AIChat);
    lv_obj_set_width(ui_PanelWIFIhiden, 37);
    lv_obj_set_height(ui_PanelWIFIhiden, 33);
    lv_obj_set_x(ui_PanelWIFIhiden, -143);
    lv_obj_set_y(ui_PanelWIFIhiden, -103);
    lv_obj_set_align(ui_PanelWIFIhiden, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWIFIhiden, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWIFIhiden, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWIFIhiden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelWIFIhiden, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelWIFIhiden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_PanelWIFIhiden);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 1);
    lv_obj_set_y(ui_Label36, -1);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "");
    lv_obj_set_style_text_font(ui_Label36, &ui_font_fontwifi, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_AIChat);
    lv_bar_set_value(ui_Bar2, 90, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 44);
    lv_obj_set_height(ui_Bar2, 17);
    lv_obj_set_x(ui_Bar2, 136);
    lv_obj_set_y(ui_Bar2, -110);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar2, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x1EB5F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_AIChat);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 134);
    lv_obj_set_y(ui_Label35, -108);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "90%");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xF1E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cat_gif = lv_gif_create(ui_AIChat);
    lv_gif_set_src(ui_cat_gif, &blue_cat_gif);
    lv_obj_align(ui_cat_gif, LV_ALIGN_BOTTOM_MID, 0, 0);

    lv_obj_add_event_cb(ui_AIChat, ui_event_AIChat, LV_EVENT_ALL, NULL);
}
