// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp_box3

#include "../ui.h"

void ui_AIchattext_screen_init(void)
{
    ui_AIchattext = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AIchattext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIchattext, lv_color_hex(0xF5E6C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIchattext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaUser = lv_textarea_create(ui_AIchattext);
    lv_obj_set_width(ui_TextAreaUser, 271);
    lv_obj_set_height(ui_TextAreaUser, 67);
    lv_obj_set_x(ui_TextAreaUser, -24);
    lv_obj_set_y(ui_TextAreaUser, -85);
    lv_obj_set_align(ui_TextAreaUser, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaUser, "");
    lv_obj_set_style_bg_color(ui_TextAreaUser, lv_color_hex(0x40DDF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextAreaUser, 60, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextAreaChat = lv_textarea_create(ui_AIchattext);
    lv_obj_set_width(ui_TextAreaChat, 271);
    lv_obj_set_height(ui_TextAreaChat, 169);
    lv_obj_set_x(ui_TextAreaChat, 22);
    lv_obj_set_y(ui_TextAreaChat, 34);
    lv_obj_set_align(ui_TextAreaChat, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaChat, "");
    lv_obj_set_style_bg_color(ui_TextAreaChat, lv_color_hex(0x21E562), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextAreaChat, 40, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Image1 = lv_img_create(ui_AIchattext);
    lv_img_set_src(ui_Image1, &ui_img_user_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image1, 135);
    lv_obj_set_y(ui_Image1, -84);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 512);

    ui_Image2 = lv_img_create(ui_AIchattext);
    lv_img_set_src(ui_Image2, &ui_img_reply_chatgpt_logo_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_Image2, -136);
    lv_obj_set_y(ui_Image2, -21);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 512);

}
