// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp_box3

#include "../ui.h"

void ui_Calendar_screen_init(void)
{
    ui_Calendar = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Calendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Calendar, lv_color_hex(0xF5E6C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Calendar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calendar1 = lv_calendar_create(ui_Calendar);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 323);
    lv_obj_set_height(ui_Calendar1, 243);
    lv_obj_set_x(ui_Calendar1, -1);
    lv_obj_set_y(ui_Calendar1, -2);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);

    ui_ChangeAIChat3 = ui_ChangeAIChat1_create(ui_Calendar);
    lv_obj_set_x(ui_ChangeAIChat3, -1);
    lv_obj_set_y(ui_ChangeAIChat3, 108);


    lv_obj_add_event_cb(ui_Calendar, ui_event_Calendar, LV_EVENT_ALL, NULL);

}
