// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp_box3

#include "../ui.h"

void ui_Memotext_screen_init(void)
{
    ui_Memotext = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Memotext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Memotext, lv_color_hex(0xF5E6C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Memotext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreamemotext = lv_textarea_create(ui_Memotext);
    lv_obj_set_width(ui_TextAreamemotext, lv_pct(100));
    lv_obj_set_height(ui_TextAreamemotext, lv_pct(80));
    lv_obj_set_x(ui_TextAreamemotext, 0);
    lv_obj_set_y(ui_TextAreamemotext, 24);
    lv_obj_set_align(ui_TextAreamemotext, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreamemotext, "您还未记备忘录");
    lv_obj_set_style_text_font(ui_TextAreamemotext, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextAreamemoname = lv_textarea_create(ui_Memotext);
    lv_obj_set_width(ui_TextAreamemoname, lv_pct(88));
    lv_obj_set_height(ui_TextAreamemoname, lv_pct(19));
    lv_obj_set_x(ui_TextAreamemoname, -20);
    lv_obj_set_y(ui_TextAreamemoname, -96);
    lv_obj_set_align(ui_TextAreamemoname, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreamemoname, "");
    lv_obj_set_style_text_font(ui_TextAreamemoname, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ChangeAIChat6 = ui_ChangeAIChat1_create(ui_Memotext);
    lv_obj_set_x(ui_ChangeAIChat6, -1);
    lv_obj_set_y(ui_ChangeAIChat6, 108);


    // ui_Keyboard1 = lv_keyboard_create(ui_Memotext);
    // lv_obj_set_width(ui_Keyboard1, lv_pct(100));
    // lv_obj_set_height(ui_Keyboard1, lv_pct(50));
    // lv_obj_set_x(ui_Keyboard1, lv_pct(0));
    // lv_obj_set_y(ui_Keyboard1, lv_pct(80));
    // lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_Button2 = lv_btn_create(ui_Memotext);
    lv_obj_set_width(ui_Button2, 35);
    lv_obj_set_height(ui_Button2, 36);
    lv_obj_set_x(ui_Button2, 140);
    lv_obj_set_y(ui_Button2, -95);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0x100F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &ui_font_Fontshanchu, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_add_event_cb(ui_TextAreamemoname, ui_event_TextAreamemoname, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Memotext, ui_event_Memotext, LV_EVENT_ALL, NULL);

}
