// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp_box3

#include "../ui.h"

void ui_Memo_screen_init(void)
{
    ui_Memo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Memo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Memo, lv_color_hex(0xF5E6C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Memo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MemoText = lv_roller_create(ui_Memo);
    lv_roller_set_options(ui_MemoText, "example1",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_MemoText, 317);
    lv_obj_set_height(ui_MemoText, 243);
    lv_obj_set_x(ui_MemoText, -1);
    lv_obj_set_y(ui_MemoText, -1);
    lv_obj_set_align(ui_MemoText, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_MemoText, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChangeAIChat9 = ui_ChangeAIChat1_create(ui_Memo);
    lv_obj_set_x(ui_ChangeAIChat9, -1);
    lv_obj_set_y(ui_ChangeAIChat9, 108);


    ui_Button3 = lv_btn_create(ui_Memo);
    lv_obj_set_width(ui_Button3, 43);
    lv_obj_set_height(ui_Button3, 38);
    lv_obj_set_x(ui_Button3, 136);
    lv_obj_set_y(ui_Button3, -1);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xE8F3BB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 250, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "√");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x050404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Memo, ui_event_Memo, LV_EVENT_ALL, NULL);

}
