// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp_box3

#include "../ui.h"

void ui_Music_screen_init(void)
{
    ui_Music = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Music, lv_color_hex(0xF5E6C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Music, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonUPMusic = lv_btn_create(ui_Music);
    lv_obj_set_width(ui_ButtonUPMusic, 64);
    lv_obj_set_height(ui_ButtonUPMusic, 64);
    lv_obj_set_x(ui_ButtonUPMusic, -95);
    lv_obj_set_y(ui_ButtonUPMusic, -25);
    lv_obj_set_align(ui_ButtonUPMusic, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonUPMusic, lv_color_hex(0xA99F9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonUPMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_ButtonUPMusic);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 1);
    lv_obj_set_y(ui_Label32, 1);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x2E2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_MusicFont1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonstartMusic = lv_btn_create(ui_Music);
    lv_obj_set_width(ui_ButtonstartMusic, 64);
    lv_obj_set_height(ui_ButtonstartMusic, 64);
    lv_obj_set_x(ui_ButtonstartMusic, 3);
    lv_obj_set_y(ui_ButtonstartMusic, -25);
    lv_obj_set_align(ui_ButtonstartMusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonstartMusic, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_ButtonstartMusic, lv_color_hex(0xA99F9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonstartMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonstartMusic, lv_color_hex(0x675FD1), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonstartMusic, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label21 = lv_label_create(ui_ButtonstartMusic);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, -1);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x2E2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_MusicFont3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtondownMusci = lv_btn_create(ui_Music);
    lv_obj_set_width(ui_ButtondownMusci, 64);
    lv_obj_set_height(ui_ButtondownMusci, 64);
    lv_obj_set_x(ui_ButtondownMusci, 99);
    lv_obj_set_y(ui_ButtondownMusci, -25);
    lv_obj_set_align(ui_ButtondownMusci, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtondownMusci, lv_color_hex(0xA99F9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtondownMusci, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_ButtondownMusci);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 1);
    lv_obj_set_y(ui_Label16, 1);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x2E2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_MusicFont2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMusicname = lv_label_create(ui_Music);
    lv_obj_set_width(ui_LabelMusicname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMusicname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMusicname, 0);
    lv_obj_set_y(ui_LabelMusicname, 17);
    lv_obj_set_align(ui_LabelMusicname, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelMusicname, "Rubia");
    lv_obj_set_style_text_font(ui_LabelMusicname, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChangeAIChat4 = ui_ChangeAIChat1_create(ui_Music);
    lv_obj_set_x(ui_ChangeAIChat4, -1);
    lv_obj_set_y(ui_ChangeAIChat4, 108);


    lv_obj_add_event_cb(ui_ButtonUPMusic, ui_event_ButtonUPMusic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonstartMusic, ui_event_ButtonstartMusic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtondownMusci, ui_event_ButtondownMusci, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Music, ui_event_Music, LV_EVENT_ALL, NULL);

}
