// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp_box3

#include "../ui.h"

void ui_Volume_screen_init(void)
{
    ui_Volume = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Volume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Volume, lv_color_hex(0xF5E6C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Volume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Volume);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -107);
    lv_obj_set_y(ui_Label14, -14);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "日历");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Volume);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -5);
    lv_obj_set_y(ui_Label17, -15);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "音乐");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Volume);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 93);
    lv_obj_set_y(ui_Label18, -16);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "音量");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Volume);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -106);
    lv_obj_set_y(ui_Label19, 97);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "天气");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Volume);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -5);
    lv_obj_set_y(ui_Label24, 95);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "备忘录");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Volume);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 95);
    lv_obj_set_y(ui_Label25, 95);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "WiFi");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Volume);
    lv_obj_set_width(ui_Panel13, 75);
    lv_obj_set_height(ui_Panel13, 64);
    lv_obj_set_x(ui_Panel13, -105);
    lv_obj_set_y(ui_Panel13, -73);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -1);
    lv_obj_set_y(ui_Label26, 1);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "");
    lv_obj_set_style_text_font(ui_Label26, &ui_font_icon1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_Volume);
    lv_obj_set_width(ui_Panel14, 76);
    lv_obj_set_height(ui_Panel14, 66);
    lv_obj_set_x(ui_Panel14, -4);
    lv_obj_set_y(ui_Panel14, -72);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 0);
    lv_obj_set_y(ui_Label27, 1);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_icon3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_Volume);
    lv_obj_set_width(ui_Panel15, 76);
    lv_obj_set_height(ui_Panel15, 66);
    lv_obj_set_x(ui_Panel15, 92);
    lv_obj_set_y(ui_Panel15, -72);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -1);
    lv_obj_set_y(ui_Label28, 0);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_icon1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_Volume);
    lv_obj_set_width(ui_Panel16, 76);
    lv_obj_set_height(ui_Panel16, 66);
    lv_obj_set_x(ui_Panel16, -108);
    lv_obj_set_y(ui_Panel16, 45);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 0);
    lv_obj_set_y(ui_Label29, -1);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_icon2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_Volume);
    lv_obj_set_width(ui_Panel17, 76);
    lv_obj_set_height(ui_Panel17, 66);
    lv_obj_set_x(ui_Panel17, -4);
    lv_obj_set_y(ui_Panel17, 44);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 0);
    lv_obj_set_y(ui_Label30, 3);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_icon3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_Volume);
    lv_obj_set_width(ui_Panel18, 76);
    lv_obj_set_height(ui_Panel18, 66);
    lv_obj_set_x(ui_Panel18, 95);
    lv_obj_set_y(ui_Panel18, 44);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -1);
    lv_obj_set_y(ui_Label31, -2);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_icon2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChangeVolume = lv_obj_create(ui_Volume);
    lv_obj_set_width(ui_ChangeVolume, 48);
    lv_obj_set_height(ui_ChangeVolume, 201);
    lv_obj_set_x(ui_ChangeVolume, 131);
    lv_obj_set_y(ui_ChangeVolume, 8);
    lv_obj_set_align(ui_ChangeVolume, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ChangeVolume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChangeVolume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChangeVolume, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChangeVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_ChangeVolume);
    lv_slider_set_value(ui_Slider2, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 38);
    lv_obj_set_height(ui_Slider2, 189);
    lv_obj_set_x(ui_Slider2, 0);
    lv_obj_set_y(ui_Slider2, -1);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xEDE9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Slider2, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Volume);
    lv_obj_set_width(ui_Panel9, 250);
    lv_obj_set_height(ui_Panel9, 236);
    lv_obj_set_x(ui_Panel9, -30);
    lv_obj_set_y(ui_Panel9, -1);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVolumevalue = lv_label_create(ui_Volume);
    lv_obj_set_width(ui_LabelVolumevalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVolumevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVolumevalue, -18);
    lv_obj_set_y(ui_LabelVolumevalue, 11);
    lv_obj_set_align(ui_LabelVolumevalue, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelVolumevalue, "50");
    lv_obj_set_style_text_font(ui_LabelVolumevalue, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChangeAIChat5 = ui_ChangeAIChat1_create(ui_Volume);
    lv_obj_set_x(ui_ChangeAIChat5, -1);
    lv_obj_set_y(ui_ChangeAIChat5, 108);


    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel9, ui_event_Panel9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelVolumevalue, ui_event_LabelVolumevalue, LV_EVENT_ALL, NULL);

}
