// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp_box3

#include "../ui.h"

void ui_WiFi_screen_init(void)
{
    ui_WiFi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WiFi, lv_color_hex(0xF5E6C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_WiFi);
    lv_obj_set_width(ui_Panel7, 316);
    lv_obj_set_height(ui_Panel7, 40);
    lv_obj_set_x(ui_Panel7, 0);
    lv_obj_set_y(ui_Panel7, -101);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 2);
    lv_obj_set_y(ui_Label15, -1);
    lv_obj_set_align(ui_Label15, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label15, "Wifi");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_WiFi);
    lv_dropdown_set_options(ui_Dropdown1,"DESKTOP-V2NVN7J 8971\n604\nSiemens\nTP-LNK506\n608\naygxy\nASUS\nH3C_32C3A0\nTPGuest_B07\nFAST_67EE88");
    lv_obj_set_width(ui_Dropdown1, 320);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 0);
    lv_obj_set_y(ui_Dropdown1, -63);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_TextArea2 = lv_textarea_create(ui_WiFi);
    lv_obj_set_width(ui_TextArea2, 280);
    lv_obj_set_height(ui_TextArea2, 40);
    lv_obj_set_x(ui_TextArea2, -19);
    lv_obj_set_y(ui_TextArea2, -25);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "");



    ui_Button1 = lv_btn_create(ui_WiFi);
    lv_obj_set_width(ui_Button1, 38);
    lv_obj_set_height(ui_Button1, 35);
    lv_obj_set_x(ui_Button1, 140);
    lv_obj_set_y(ui_Button1, -25);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "√");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x050404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_WiFi);
    lv_obj_set_width(ui_Keyboard2, lv_pct(100));
    lv_obj_set_height(ui_Keyboard2, lv_pct(50));
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 185);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_ChangeAIChat7 = ui_ChangeAIChat1_create(ui_WiFi);
    lv_obj_set_x(ui_ChangeAIChat7, -1);
    lv_obj_set_y(ui_ChangeAIChat7, 108);


    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFi, ui_event_WiFi, LV_EVENT_ALL, NULL);

}
