// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_LabelDate;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Labelwakenet;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_cat_gif;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Calendar;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_MusicName;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(blue_cat_gif);
LV_IMG_DECLARE(ui_img_settings_icon_png);    // assets/settings_icon.png
LV_IMG_DECLARE(ui_img_cat_wait_png);    // assets/cat_wait.png
LV_IMG_DECLARE(ui_img_forward_media_png);    // assets/forward_media.png
LV_IMG_DECLARE(ui_img_backward_media_png);    // assets/backward_media.png
LV_IMG_DECLARE(ui_img_headphones_music_png);    // assets/headphones_music.png
LV_IMG_DECLARE(ui_img_kapigongde1_png);    // assets/kapigongde1.png
LV_IMG_DECLARE(ui_img_kapigongde2_png);    // assets/kapigongde2.png
LV_IMG_DECLARE(ui_img_keyboard2_png);    // assets/keyboard2.png
LV_IMG_DECLARE(ui_img_rmk_logo_60_png);    // assets/rmk_logo_60.png
LV_IMG_DECLARE(ui_img_sao2_png);    // assets/SaO2.png


LV_FONT_DECLARE(ui_font_HAPanel);
LV_FONT_DECLARE(ui_font_weatherWeek);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
